
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.2 EDK_MS2.63c
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_DIP_SWITCHES_8BITS_DEVICE_ID,
		XPAR_DIP_SWITCHES_8BITS_BASEADDR,
		XPAR_DIP_SWITCHES_8BITS_INTERRUPT_PRESENT,
		XPAR_DIP_SWITCHES_8BITS_IS_DUAL
	},
	{
		XPAR_I2C_BUS_DEVICE_ID,
		XPAR_I2C_BUS_BASEADDR,
		XPAR_I2C_BUS_INTERRUPT_PRESENT,
		XPAR_I2C_BUS_IS_DUAL
	},
	{
		XPAR_LEDS_8BITS_DEVICE_ID,
		XPAR_LEDS_8BITS_BASEADDR,
		XPAR_LEDS_8BITS_INTERRUPT_PRESENT,
		XPAR_LEDS_8BITS_IS_DUAL
	},
	{
		XPAR_PUSH_BUTTONS_5BITS_DEVICE_ID,
		XPAR_PUSH_BUTTONS_5BITS_BASEADDR,
		XPAR_PUSH_BUTTONS_5BITS_INTERRUPT_PRESENT,
		XPAR_PUSH_BUTTONS_5BITS_IS_DUAL
	},
	{
		XPAR_VHDCI_CONN_DEVICE_ID,
		XPAR_VHDCI_CONN_BASEADDR,
		XPAR_VHDCI_CONN_INTERRUPT_PRESENT,
		XPAR_VHDCI_CONN_IS_DUAL
	}
};


